### PR TITLE
Registerable event added: on_pick_up.

### PR DESCRIPTION
**Pull request by Unarelith**
What the title says. Since the engine doesn't provide this callback, I thought it could be nice to have it here.

### CODE REVIEW

**Comment by HybridDog** [comment]
You should do this in a separate mod, see #17.

**Comment by Unarelith** [comment]
@HybridDog well I disagree with what have been said on #17, I really need a global "on_item_pickup" for my `quest_lib` mod, since I need to check that the player got specific items.

There's currently no other way than adding this here, and since the PR in minetest could take time, I thought it could be nice to have this.

**Comment by HybridDog** [comment]
> There's currently no other way than adding this here

No, you can override the on_punch function of the item definition (originally defined at https://github.com/minetest/minetest/blob/master/builtin/game/item_entity.lua#L216).

What you have done here only affects item picked up automatically by this mod. If a player clicks an item to pick it, the functions in pickup_callbacks are not executed.

This untested code could do what you need. You can change it to test and pass the itemstring if you want.
```Lua
local entdef = minetest.registered_entities["__builtin:item"]
local actual_on_punch = entdef.on_punch
entdef.on_punch = function(self, player)
	for i = 1,#pickup_callbacks do
		local rv = pickup_callbacks[i](self, player)
		if rv == false then
			-- Abort when a callback explicitly returns false
			return
		end
		if rv == true then
			-- Do not execute other pickup callbacks if the current one
			-- explicitly returned true
			break
		end
	end
	-- Do the pickup
	actual_on_punch(self, player)
end
```

**Comment by Unarelith** [comment]
> What you have done here only affects item picked up automatically by this mod. If a player clicks an item to pick it, the functions in pickup_callbacks are not executed.

Actually this is exactly the behaviour I'm looking for, but nvm I'll override `__builtin:item`, feels really hacky though

**Comment by HybridDog** [comment]
To find out if the item is picked by this mod, an item_drop_picked boolean field could be added to ent before calling on_punch.

**Comment by tacotexmex** [comment]
> but nvm I'll override __builtin:item

@Quent42340 Did you ever get to it? I want this too.

**Comment by Unarelith** [comment]
@tacotexmex Nope, I still use the code from this PR, it's cleaner and easier.

**Comment by tacotexmex** [comment]
Can we please write this mod, it would be great companion to item_drop! I’ve also thought about a feature of protection checking of dropped items so that individuals or groups may safely throw around items without others or opponents grabbing their stuff.

**Comment by HybridDog** [comment]
Here is the mod: https://github.com/HybridDog/item_helpers/blob/master/init.lua
It enables the item_helpers.can_pick field to item definitions where you can disallow picking the item under certain circumstances and you can do it for all items (see the examples).

**Comment by tacotexmex** [comment]
That's super helpful HD, thank you <3

**Pull request closed without merging**
